format = """
[$custom]()\
[$username]()\
[]()\
[]()\
[$directory]()\
[ ]()
"""

add_newline = false

[custom.snowflake]
format = "[$symbol]($style)"
symbol = "  "
style = "bg:#bfcfff fg:#474e66"
when = "echo 0"

[username]
format = "[$user ]($style)"
style_user = "bg:#bfcfff fg:#474e66"
show_always = true

[directory]
format = "[ $path ]($style)"
style = "bg:#bfcfff fg:#474e66"
truncation_length = 1
truncation_symbol = ".."
